// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_Air_Conditioner_screen_init();
    ui_Vaccume_Cleaner_screen_init();
    ui_Water_Purifier_screen_init();
    ui_Exhaust__screen_init();
    ui_bar_screen_init();
    ui_acerror_screen_init();
    ui_vcerror_screen_init();
    ui_roerror_screen_init();
    ui_exerror_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}

void ui_destroy(void)
{
    ui_Home_screen_destroy();
    ui_Air_Conditioner_screen_destroy();
    ui_Vaccume_Cleaner_screen_destroy();
    ui_Water_Purifier_screen_destroy();
    ui_Exhaust__screen_destroy();
    ui_bar_screen_destroy();
    ui_acerror_screen_destroy();
    ui_vcerror_screen_destroy();
    ui_roerror_screen_destroy();
    ui_exerror_screen_destroy();
}
