// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Home.h"
#include "ui_Air_Conditioner.h"
#include "ui_Vaccume_Cleaner.h"
#include "ui_Water_Purifier.h"
#include "ui_Exhaust_.h"
#include "ui_bar.h"
#include "ui_acerror.h"
#include "ui_vcerror.h"
#include "ui_roerror.h"
#include "ui_exerror.h"

///////////////////// VARIABLES ////////////////////
extern bool is_ac_month_changed;
extern bool is_ac_alert;

extern bool is_ro_month_changed;
extern bool is_ro_alert;

extern bool is_vc_month_changed;
extern bool is_vc_alert;

extern bool is_ex_month_changed;
extern bool is_ex_alert;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1601027584);    // assets/ac-removebg-preview.png
LV_IMG_DECLARE(ui_img_2146812223);    // assets/Ex-removebg-preview.png
LV_IMG_DECLARE(ui_img_1371760645);    // assets/RO-removebg-preview.png
LV_IMG_DECLARE(ui_img_605809133);    // assets/VC-removebg-preview.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
