// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_acerror = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Okayac = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions

bool is_ac_alert = false;

void ui_event_Okayac(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
        is_ac_alert = false;
    }
}

// build funtions

void ui_acerror_screen_init(void)
{
    ui_acerror = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_acerror, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_img_create(ui_acerror);
    lv_img_set_src(ui_Image18, &ui_img_1601027584);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 316
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 316
    lv_obj_set_x(ui_Image18, -2);
    lv_obj_set_y(ui_Image18, -53);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image18, 100);

    ui_Label4 = lv_label_create(ui_acerror);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 1);
    lv_obj_set_y(ui_Label4, 8);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Need Maintenance");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Okayac = lv_btn_create(ui_acerror);
    lv_obj_set_width(ui_Okayac, 100);
    lv_obj_set_height(ui_Okayac, 50);
    lv_obj_set_x(ui_Okayac, 0);
    lv_obj_set_y(ui_Okayac, 63);
    lv_obj_set_align(ui_Okayac, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Okayac, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Okayac, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_acerror);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -2);
    lv_obj_set_y(ui_Label5, 64);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "OKAY");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Okayac, ui_event_Okayac, LV_EVENT_ALL, NULL);

}

void ui_acerror_screen_destroy(void)
{
    if(ui_acerror) lv_obj_del(ui_acerror);

    // NULL screen variables
    ui_acerror = NULL;
    ui_Image18 = NULL;
    ui_Label4 = NULL;
    ui_Okayac = NULL;
    ui_Label5 = NULL;

}
