// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ACERROR_H
#define UI_ACERROR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_acerror
extern void ui_acerror_screen_init(void);
extern void ui_acerror_screen_destroy(void);
extern lv_obj_t * ui_acerror;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Label4;
extern void ui_event_Okayac(lv_event_t * e);
extern lv_obj_t * ui_Okayac;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

//extern bool is_ac_alert;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
