// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_AIR_CONDITIONER_H
#define UI_AIR_CONDITIONER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Air_Conditioner
extern void ui_Air_Conditioner_screen_init(void);
extern void ui_Air_Conditioner_screen_destroy(void);
extern void ui_event_Air_Conditioner(lv_event_t * e);
extern lv_obj_t * ui_Air_Conditioner;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Image10;
extern void ui_event_Done1(lv_event_t * e);
extern lv_obj_t * ui_Done1;
extern lv_obj_t * ui_Done;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Done1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
