// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Done1;
lv_obj_t * ui_Air_Conditioner = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Done1 = NULL;
lv_obj_t * ui_Done = NULL;
// event funtions
void ui_event_Air_Conditioner(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
    }
}

bool is_ac_month_changed = false;

void ui_event_Done1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
        is_ac_month_changed = true;
    }
}

// build funtions

void ui_Air_Conditioner_screen_init(void)
{
    ui_Air_Conditioner = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Air_Conditioner, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dropdown1 = lv_dropdown_create(ui_Air_Conditioner);
    lv_dropdown_set_options(ui_Dropdown1,
                            "No select\n1 Month\n2 Month\n3 Month\n4 Month\n5 Month\n6 Month\n7 Month\n8 Month\n9 Month\n10 Month\n11 Month\n12 Month\n13 Month\n14 Month\n15 Month\n16 Month\n17 Month\n18 Month\n19 Month\n20 Month\n21 Month\n22 Month\n23 Month\n24 Month\n");
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 3);
    lv_obj_set_y(ui_Dropdown1, -51);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Image10 = lv_img_create(ui_Air_Conditioner);
    lv_img_set_src(ui_Image10, &ui_img_1601027584);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 316
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 316
    lv_obj_set_x(ui_Image10, -3);
    lv_obj_set_y(ui_Image10, 12);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image10, 100);

    ui_Done1 = lv_btn_create(ui_Air_Conditioner);
    lv_obj_set_width(ui_Done1, 81);
    lv_obj_set_height(ui_Done1, 37);
    lv_obj_set_x(ui_Done1, 0);
    lv_obj_set_y(ui_Done1, 82);
    lv_obj_set_align(ui_Done1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Done1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Done1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Done = lv_label_create(ui_Air_Conditioner);
    lv_obj_set_width(ui_Done, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Done, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Done, 0);
    lv_obj_set_y(ui_Done, 82);
    lv_obj_set_align(ui_Done, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Done, "SAVE");

    lv_obj_add_event_cb(ui_Done1, ui_event_Done1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Air_Conditioner, ui_event_Air_Conditioner, LV_EVENT_ALL, NULL);
    uic_Done1 = ui_Done1;

}

void ui_Air_Conditioner_screen_destroy(void)
{
    if(ui_Air_Conditioner) lv_obj_del(ui_Air_Conditioner);

    // NULL screen variables
    ui_Air_Conditioner = NULL;
    ui_Dropdown1 = NULL;
    ui_Image10 = NULL;
    uic_Done1 = NULL;
    ui_Done1 = NULL;
    ui_Done = NULL;

}
