// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_bar = NULL;
lv_obj_t * ui_bar_ac = NULL;
lv_obj_t * ui_bar_ro = NULL;
lv_obj_t * ui_bar_vc = NULL;
lv_obj_t * ui_bar_ex = NULL;
lv_obj_t * ui_EXbar = NULL;
lv_obj_t * ui_RObar = NULL;
lv_obj_t * ui_VCbar = NULL;
lv_obj_t * ui_ACbar = NULL;
// event funtions
void ui_event_bar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
    }
}

// build funtions

void ui_bar_screen_init(void)
{
    ui_bar = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bar_ac = lv_bar_create(ui_bar);
    lv_bar_set_value(ui_bar_ac, 30, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_bar_ac, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_bar_ac, 150);
    lv_obj_set_height(ui_bar_ac, 10);
    lv_obj_set_x(ui_bar_ac, 16);
    lv_obj_set_y(ui_bar_ac, -57);
    lv_obj_set_align(ui_bar_ac, LV_ALIGN_CENTER);

    ui_bar_ro = lv_bar_create(ui_bar);
    lv_bar_set_value(ui_bar_ro, 60, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_bar_ro, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_bar_ro, 150);
    lv_obj_set_height(ui_bar_ro, 10);
    lv_obj_set_x(ui_bar_ro, 15);
    lv_obj_set_y(ui_bar_ro, -15);
    lv_obj_set_align(ui_bar_ro, LV_ALIGN_CENTER);

    ui_bar_vc = lv_bar_create(ui_bar);
    lv_bar_set_value(ui_bar_vc, 90, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_bar_vc, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_bar_vc, 150);
    lv_obj_set_height(ui_bar_vc, 10);
    lv_obj_set_x(ui_bar_vc, 15);
    lv_obj_set_y(ui_bar_vc, 24);
    lv_obj_set_align(ui_bar_vc, LV_ALIGN_CENTER);

    ui_bar_ex = lv_bar_create(ui_bar);
    lv_bar_set_value(ui_bar_ex, 10, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_bar_ex, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_bar_ex, 150);
    lv_obj_set_height(ui_bar_ex, 10);
    lv_obj_set_x(ui_bar_ex, 16);
    lv_obj_set_y(ui_bar_ex, 67);
    lv_obj_set_align(ui_bar_ex, LV_ALIGN_CENTER);

    ui_EXbar = lv_img_create(ui_bar);
    lv_img_set_src(ui_EXbar, &ui_img_2146812223);
    lv_obj_set_width(ui_EXbar, LV_SIZE_CONTENT);   /// 324
    lv_obj_set_height(ui_EXbar, LV_SIZE_CONTENT);    /// 324
    lv_obj_set_x(ui_EXbar, -77);
    lv_obj_set_y(ui_EXbar, 67);
    lv_obj_set_align(ui_EXbar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EXbar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_EXbar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_EXbar, 30);

    ui_RObar = lv_img_create(ui_bar);
    lv_img_set_src(ui_RObar, &ui_img_1371760645);
    lv_obj_set_width(ui_RObar, LV_SIZE_CONTENT);   /// 298
    lv_obj_set_height(ui_RObar, LV_SIZE_CONTENT);    /// 298
    lv_obj_set_x(ui_RObar, -80);
    lv_obj_set_y(ui_RObar, -18);
    lv_obj_set_align(ui_RObar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RObar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RObar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_RObar, 30);

    ui_VCbar = lv_img_create(ui_bar);
    lv_img_set_src(ui_VCbar, &ui_img_605809133);
    lv_obj_set_width(ui_VCbar, LV_SIZE_CONTENT);   /// 322
    lv_obj_set_height(ui_VCbar, LV_SIZE_CONTENT);    /// 322
    lv_obj_set_x(ui_VCbar, -76);
    lv_obj_set_y(ui_VCbar, 24);
    lv_obj_set_align(ui_VCbar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VCbar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VCbar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_VCbar, 30);

    ui_ACbar = lv_img_create(ui_bar);
    lv_img_set_src(ui_ACbar, &ui_img_1601027584);
    lv_obj_set_width(ui_ACbar, LV_SIZE_CONTENT);   /// 316
    lv_obj_set_height(ui_ACbar, LV_SIZE_CONTENT);    /// 316
    lv_obj_set_x(ui_ACbar, -80);
    lv_obj_set_y(ui_ACbar, -57);
    lv_obj_set_align(ui_ACbar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ACbar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ACbar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ACbar, 30);

    lv_obj_add_event_cb(ui_bar, ui_event_bar, LV_EVENT_ALL, NULL);

}

void ui_bar_screen_destroy(void)
{
    if(ui_bar) lv_obj_del(ui_bar);

    // NULL screen variables
    ui_bar = NULL;
    ui_bar_ac = NULL;
    ui_bar_ro = NULL;
    ui_bar_vc = NULL;
    ui_bar_ex = NULL;
    ui_EXbar = NULL;
    ui_RObar = NULL;
    ui_VCbar = NULL;
    ui_ACbar = NULL;

}
