// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_BAR_H
#define UI_BAR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_bar
extern void ui_bar_screen_init(void);
extern void ui_bar_screen_destroy(void);
extern void ui_event_bar(lv_event_t * e);
extern lv_obj_t * ui_bar;
extern lv_obj_t * ui_bar_ac;
extern lv_obj_t * ui_bar_ro;
extern lv_obj_t * ui_bar_vc;
extern lv_obj_t * ui_bar_ex;
extern lv_obj_t * ui_EXbar;
extern lv_obj_t * ui_RObar;
extern lv_obj_t * ui_VCbar;
extern lv_obj_t * ui_ACbar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

