// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_EXHAUST__H
#define UI_EXHAUST__H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Exhaust_
extern void ui_Exhaust__screen_init(void);
extern void ui_Exhaust__screen_destroy(void);
extern void ui_event_Exhaust_(lv_event_t * e);
extern lv_obj_t * ui_Exhaust_;
extern lv_obj_t * ui_Dropdown3;
extern lv_obj_t * ui_Image13;
extern void ui_event_Done8(lv_event_t * e);
extern lv_obj_t * ui_Done8;
extern lv_obj_t * ui_Done5;
// CUSTOM VARIABLES

//bool is_ex_month_changed = false;
//bool is_ex_alert = false;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
