// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_exerror = NULL;
lv_obj_t * ui_Image22 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Okayac4 = NULL;
lv_obj_t * ui_Label10 = NULL;
// event funtions

bool is_ex_alert = false;

void ui_event_Okayac4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
        is_ex_alert = false;
        is_ex_month_changed = true;
    }
}

// build funtions

void ui_exerror_screen_init(void)
{
    ui_exerror = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_exerror, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image22 = lv_img_create(ui_exerror);
    lv_img_set_src(ui_Image22, &ui_img_2146812223);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 324
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 324
    lv_obj_set_x(ui_Image22, 2);
    lv_obj_set_y(ui_Image22, -56);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image22, 100);

    ui_Label7 = lv_label_create(ui_exerror);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 1);
    lv_obj_set_y(ui_Label7, 13);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Need Maintenance");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label7, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Okayac4 = lv_btn_create(ui_exerror);
    lv_obj_set_width(ui_Okayac4, 100);
    lv_obj_set_height(ui_Okayac4, 50);
    lv_obj_set_x(ui_Okayac4, 0);
    lv_obj_set_y(ui_Okayac4, 63);
    lv_obj_set_align(ui_Okayac4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Okayac4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Okayac4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_exerror);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -2);
    lv_obj_set_y(ui_Label10, 64);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "OKAY");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Okayac4, ui_event_Okayac4, LV_EVENT_ALL, NULL);

}

void ui_exerror_screen_destroy(void)
{
    if(ui_exerror) lv_obj_del(ui_exerror);

    // NULL screen variables
    ui_exerror = NULL;
    ui_Image22 = NULL;
    ui_Label7 = NULL;
    ui_Okayac4 = NULL;
    ui_Label10 = NULL;

}
