// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Exhaust_ = NULL;
lv_obj_t * ui_Dropdown3 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Done8 = NULL;
lv_obj_t * ui_Done5 = NULL;
// event funtions
void ui_event_Exhaust_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
    }
}


bool is_ex_month_changed = false;

void ui_event_Done8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
        is_ex_month_changed = true;
    }
}

// build funtions

void ui_Exhaust__screen_init(void)
{
    ui_Exhaust_ = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Exhaust_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dropdown3 = lv_dropdown_create(ui_Exhaust_);
    lv_dropdown_set_options(ui_Dropdown3,
                            "No select\n1 Month\n2 Month\n3 Month\n4 Month\n5 Month\n6 Month\n7 Month\n8 Month\n9 Month\n10 Month\n11 Month\n12 Month\n13 Month\n14 Month\n15 Month\n16 Month\n17 Month\n18 Month\n19 Month\n20 Month\n21 Month\n22 Month\n23 Month\n24 Month\n");
    lv_obj_set_width(ui_Dropdown3, 150);
    lv_obj_set_height(ui_Dropdown3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown3, -2);
    lv_obj_set_y(ui_Dropdown3, -57);
    lv_obj_set_align(ui_Dropdown3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Image13 = lv_img_create(ui_Exhaust_);
    lv_img_set_src(ui_Image13, &ui_img_2146812223);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 324
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 324
    lv_obj_set_x(ui_Image13, -3);
    lv_obj_set_y(ui_Image13, 15);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image13, 80);

    ui_Done8 = lv_btn_create(ui_Exhaust_);
    lv_obj_set_width(ui_Done8, 81);
    lv_obj_set_height(ui_Done8, 37);
    lv_obj_set_x(ui_Done8, 1);
    lv_obj_set_y(ui_Done8, 82);
    lv_obj_set_align(ui_Done8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Done8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Done8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Done5 = lv_label_create(ui_Exhaust_);
    lv_obj_set_width(ui_Done5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Done5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Done5, 0);
    lv_obj_set_y(ui_Done5, 82);
    lv_obj_set_align(ui_Done5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Done5, "SAVE");

    lv_obj_add_event_cb(ui_Done8, ui_event_Done8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Exhaust_, ui_event_Exhaust_, LV_EVENT_ALL, NULL);

}

void ui_Exhaust__screen_destroy(void)
{
    if(ui_Exhaust_) lv_obj_del(ui_Exhaust_);

    // NULL screen variables
    ui_Exhaust_ = NULL;
    ui_Dropdown3 = NULL;
    ui_Image13 = NULL;
    ui_Done8 = NULL;
    ui_Done5 = NULL;

}
