// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_EXERROR_H
#define UI_EXERROR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_exerror
extern void ui_exerror_screen_init(void);
extern void ui_exerror_screen_destroy(void);
extern lv_obj_t * ui_exerror;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Label7;
extern void ui_event_Okayac4(lv_event_t * e);
extern lv_obj_t * ui_Okayac4;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

//extern bool is_ex_alert;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
