// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_airconditioner = NULL;
lv_obj_t * ui_exhaust = NULL;
lv_obj_t * ui_waterpurifier = NULL;
lv_obj_t * ui_Vaccune = NULL;
// event funtions
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
    }
}

void ui_event_Panel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
    }
}

void ui_event_airconditioner(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Air_Conditioner, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Air_Conditioner_screen_init);
    }
}

void ui_event_exhaust(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Exhaust_, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Exhaust__screen_init);
    }
}

void ui_event_waterpurifier(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Water_Purifier, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Water_Purifier_screen_init);
    }
}

void ui_event_Vaccune(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Vaccume_Cleaner, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Vaccume_Cleaner_screen_init);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_Panel1, 309);
    lv_obj_set_height(ui_Panel1, 272);
    lv_obj_set_x(ui_Panel1, -1);
    lv_obj_set_y(ui_Panel1, -11);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_airconditioner = lv_img_create(ui_Home);
    lv_img_set_src(ui_airconditioner, &ui_img_1601027584);
    lv_obj_set_width(ui_airconditioner, LV_SIZE_CONTENT);   /// 316
    lv_obj_set_height(ui_airconditioner, LV_SIZE_CONTENT);    /// 316
    lv_obj_set_x(ui_airconditioner, -48);
    lv_obj_set_y(ui_airconditioner, -46);
    lv_obj_set_align(ui_airconditioner, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_airconditioner, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_airconditioner, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_airconditioner, 50);

    ui_exhaust = lv_img_create(ui_Home);
    lv_img_set_src(ui_exhaust, &ui_img_2146812223);
    lv_obj_set_width(ui_exhaust, LV_SIZE_CONTENT);   /// 324
    lv_obj_set_height(ui_exhaust, LV_SIZE_CONTENT);    /// 324
    lv_obj_set_x(ui_exhaust, -47);
    lv_obj_set_y(ui_exhaust, 40);
    lv_obj_set_align(ui_exhaust, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_exhaust, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_exhaust, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_exhaust, 50);

    ui_waterpurifier = lv_img_create(ui_Home);
    lv_img_set_src(ui_waterpurifier, &ui_img_1371760645);
    lv_obj_set_width(ui_waterpurifier, LV_SIZE_CONTENT);   /// 298
    lv_obj_set_height(ui_waterpurifier, LV_SIZE_CONTENT);    /// 298
    lv_obj_set_x(ui_waterpurifier, 44);
    lv_obj_set_y(ui_waterpurifier, -48);
    lv_obj_set_align(ui_waterpurifier, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_waterpurifier, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_waterpurifier, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_waterpurifier, 55);

    ui_Vaccune = lv_img_create(ui_Home);
    lv_img_set_src(ui_Vaccune, &ui_img_605809133);
    lv_obj_set_width(ui_Vaccune, LV_SIZE_CONTENT);   /// 322
    lv_obj_set_height(ui_Vaccune, LV_SIZE_CONTENT);    /// 322
    lv_obj_set_x(ui_Vaccune, 44);
    lv_obj_set_y(ui_Vaccune, 37);
    lv_obj_set_align(ui_Vaccune, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Vaccune, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Vaccune, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Vaccune, 50);

    lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_airconditioner, ui_event_airconditioner, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_exhaust, ui_event_exhaust, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_waterpurifier, ui_event_waterpurifier, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Vaccune, ui_event_Vaccune, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home, ui_event_Home, LV_EVENT_ALL, NULL);

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    ui_Home = NULL;
    ui_Panel1 = NULL;
    ui_airconditioner = NULL;
    ui_exhaust = NULL;
    ui_waterpurifier = NULL;
    ui_Vaccune = NULL;

}
