// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern void ui_event_airconditioner(lv_event_t * e);
extern lv_obj_t * ui_airconditioner;
extern void ui_event_exhaust(lv_event_t * e);
extern lv_obj_t * ui_exhaust;
extern void ui_event_waterpurifier(lv_event_t * e);
extern lv_obj_t * ui_waterpurifier;
extern void ui_event_Vaccune(lv_event_t * e);
extern lv_obj_t * ui_Vaccune;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

