// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_roerror = NULL;
lv_obj_t * ui_Image21 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Okayac3 = NULL;
lv_obj_t * ui_Label9 = NULL;
// event funtions
bool is_ro_alert = false;

void ui_event_Okayac3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
        is_ro_alert = false;
        is_ro_month_changed = true;
    }
}

// build funtions

void ui_roerror_screen_init(void)
{
    ui_roerror = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_roerror, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image21 = lv_img_create(ui_roerror);
    lv_img_set_src(ui_Image21, &ui_img_1371760645);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 298
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 298
    lv_obj_set_x(ui_Image21, 8);
    lv_obj_set_y(ui_Image21, -55);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image21, 100);

    ui_Label6 = lv_label_create(ui_roerror);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 1);
    lv_obj_set_y(ui_Label6, 14);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Need Maintenance");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label6, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Okayac3 = lv_btn_create(ui_roerror);
    lv_obj_set_width(ui_Okayac3, 100);
    lv_obj_set_height(ui_Okayac3, 50);
    lv_obj_set_x(ui_Okayac3, 0);
    lv_obj_set_y(ui_Okayac3, 63);
    lv_obj_set_align(ui_Okayac3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Okayac3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Okayac3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_roerror);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -2);
    lv_obj_set_y(ui_Label9, 64);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "OKAY");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Okayac3, ui_event_Okayac3, LV_EVENT_ALL, NULL);

}

void ui_roerror_screen_destroy(void)
{
    if(ui_roerror) lv_obj_del(ui_roerror);

    // NULL screen variables
    ui_roerror = NULL;
    ui_Image21 = NULL;
    ui_Label6 = NULL;
    ui_Okayac3 = NULL;
    ui_Label9 = NULL;

}
