// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ROERROR_H
#define UI_ROERROR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_roerror
extern void ui_roerror_screen_init(void);
extern void ui_roerror_screen_destroy(void);
extern lv_obj_t * ui_roerror;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Label6;
extern void ui_event_Okayac3(lv_event_t * e);
extern lv_obj_t * ui_Okayac3;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES

//extern bool is_ro_alert;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
