// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_VCERROR_H
#define UI_VCERROR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_vcerror
extern void ui_vcerror_screen_init(void);
extern void ui_vcerror_screen_destroy(void);
extern lv_obj_t * ui_vcerror;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Label2;
extern void ui_event_Okayac2(lv_event_t * e);
extern lv_obj_t * ui_Okayac2;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

//extern bool is_vc_alert;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
