// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_vcerror = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Okayac2 = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions

bool is_vc_alert = false;

void ui_event_Okayac2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
        is_vc_alert = false;
        is_vc_month_changed = true;
    }
}

// build funtions

void ui_vcerror_screen_init(void)
{
    ui_vcerror = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_vcerror, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_img_create(ui_vcerror);
    lv_img_set_src(ui_Image20, &ui_img_605809133);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 322
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 322
    lv_obj_set_x(ui_Image20, 1);
    lv_obj_set_y(ui_Image20, -51);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image20, 100);

    ui_Label2 = lv_label_create(ui_vcerror);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 1);
    lv_obj_set_y(ui_Label2, 15);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Need Maintenance");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Okayac2 = lv_btn_create(ui_vcerror);
    lv_obj_set_width(ui_Okayac2, 100);
    lv_obj_set_height(ui_Okayac2, 50);
    lv_obj_set_x(ui_Okayac2, 0);
    lv_obj_set_y(ui_Okayac2, 63);
    lv_obj_set_align(ui_Okayac2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Okayac2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Okayac2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_vcerror);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -2);
    lv_obj_set_y(ui_Label8, 64);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "OKAY");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Okayac2, ui_event_Okayac2, LV_EVENT_ALL, NULL);

}

void ui_vcerror_screen_destroy(void)
{
    if(ui_vcerror) lv_obj_del(ui_vcerror);

    // NULL screen variables
    ui_vcerror = NULL;
    ui_Image20 = NULL;
    ui_Label2 = NULL;
    ui_Okayac2 = NULL;
    ui_Label8 = NULL;

}
