// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Vaccume_Cleaner = NULL;
lv_obj_t * ui_Dropdown2 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Done6 = NULL;
lv_obj_t * ui_Done3 = NULL;
// event funtions
void ui_event_Vaccume_Cleaner(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
    }
}

bool is_vc_month_changed = false;

void ui_event_Done6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
        is_vc_month_changed = true;
    }
}

void ui_event_Done3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
    }
}

// build funtions

void ui_Vaccume_Cleaner_screen_init(void)
{
    ui_Vaccume_Cleaner = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Vaccume_Cleaner, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dropdown2 = lv_dropdown_create(ui_Vaccume_Cleaner);
    lv_dropdown_set_options(ui_Dropdown2,
                            "No select\n1 Month\n2 Month\n3 Month\n4 Month\n5 Month\n6 Month\n7 Month\n8 Month\n9 Month\n10 Month\n11 Month\n12 Month\n13 Month\n14 Month\n15 Month\n16 Month\n17 Month\n18 Month\n19 Month\n20 Month\n21 Month\n22 Month\n23 Month\n24 Month\n");
    lv_obj_set_width(ui_Dropdown2, 150);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 3);
    lv_obj_set_y(ui_Dropdown2, -56);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Image11 = lv_img_create(ui_Vaccume_Cleaner);
    lv_img_set_src(ui_Image11, &ui_img_605809133);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 322
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 322
    lv_obj_set_x(ui_Image11, -1);
    lv_obj_set_y(ui_Image11, 18);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image11, 80);

    ui_Done6 = lv_btn_create(ui_Vaccume_Cleaner);
    lv_obj_set_width(ui_Done6, 81);
    lv_obj_set_height(ui_Done6, 37);
    lv_obj_set_x(ui_Done6, 0);
    lv_obj_set_y(ui_Done6, 82);
    lv_obj_set_align(ui_Done6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Done6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Done6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Done3 = lv_label_create(ui_Vaccume_Cleaner);
    lv_obj_set_width(ui_Done3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Done3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Done3, 0);
    lv_obj_set_y(ui_Done3, 82);
    lv_obj_set_align(ui_Done3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Done3, "SAVE");

    lv_obj_add_event_cb(ui_Done6, ui_event_Done6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Done3, ui_event_Done3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Vaccume_Cleaner, ui_event_Vaccume_Cleaner, LV_EVENT_ALL, NULL);

}

void ui_Vaccume_Cleaner_screen_destroy(void)
{
    if(ui_Vaccume_Cleaner) lv_obj_del(ui_Vaccume_Cleaner);

    // NULL screen variables
    ui_Vaccume_Cleaner = NULL;
    ui_Dropdown2 = NULL;
    ui_Image11 = NULL;
    ui_Done6 = NULL;
    ui_Done3 = NULL;

}
