// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_VACCUME_CLEANER_H
#define UI_VACCUME_CLEANER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Vaccume_Cleaner
extern void ui_Vaccume_Cleaner_screen_init(void);
extern void ui_Vaccume_Cleaner_screen_destroy(void);
extern void ui_event_Vaccume_Cleaner(lv_event_t * e);
extern lv_obj_t * ui_Vaccume_Cleaner;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_Image11;
extern void ui_event_Done6(lv_event_t * e);
extern lv_obj_t * ui_Done6;
extern void ui_event_Done3(lv_event_t * e);
extern lv_obj_t * ui_Done3;

//bool is_vc_month_changed = false;
//bool is_vc_alert = false;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
