// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_WATER_PURIFIER_H
#define UI_WATER_PURIFIER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Water_Purifier
extern void ui_Water_Purifier_screen_init(void);
extern void ui_Water_Purifier_screen_destroy(void);
extern void ui_event_Water_Purifier(lv_event_t * e);
extern lv_obj_t * ui_Water_Purifier;
extern lv_obj_t * ui_Dropdown4;
extern lv_obj_t * ui_Image12;
extern void ui_event_Done7(lv_event_t * e);
extern lv_obj_t * ui_Done7;
extern lv_obj_t * ui_Done4;

//bool is_ro_month_changed = false;
//bool is_ro_alert = false;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
