// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Water_Purifier = NULL;
lv_obj_t * ui_Dropdown4 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Done7 = NULL;
lv_obj_t * ui_Done4 = NULL;
// event funtions
void ui_event_Water_Purifier(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
    }
}

bool is_ro_month_changed = false;

void ui_event_Done7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_bar_screen_init);
        is_ro_month_changed = true;
    }
}

// build funtions

void ui_Water_Purifier_screen_init(void)
{
    ui_Water_Purifier = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Water_Purifier, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dropdown4 = lv_dropdown_create(ui_Water_Purifier);
    lv_dropdown_set_options(ui_Dropdown4,
                            "No select\n1 Month\n2 Month\n3 Month\n4 Month\n5 Month\n6 Month\n7 Month\n8 Month\n9 Month\n10 Month\n11 Month\n12 Month\n13 Month\n14 Month\n15 Month\n16 Month\n17 Month\n18 Month\n19 Month\n20 Month\n21 Month\n22 Month\n23 Month\n24 Month\n");
    lv_obj_set_width(ui_Dropdown4, 150);
    lv_obj_set_height(ui_Dropdown4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown4, 1);
    lv_obj_set_y(ui_Dropdown4, -58);
    lv_obj_set_align(ui_Dropdown4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Image12 = lv_img_create(ui_Water_Purifier);
    lv_img_set_src(ui_Image12, &ui_img_1371760645);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 298
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 298
    lv_obj_set_x(ui_Image12, -1);
    lv_obj_set_y(ui_Image12, 16);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image12, 80);

    ui_Done7 = lv_btn_create(ui_Water_Purifier);
    lv_obj_set_width(ui_Done7, 81);
    lv_obj_set_height(ui_Done7, 37);
    lv_obj_set_x(ui_Done7, 0);
    lv_obj_set_y(ui_Done7, 82);
    lv_obj_set_align(ui_Done7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Done7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Done7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Done4 = lv_label_create(ui_Water_Purifier);
    lv_obj_set_width(ui_Done4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Done4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Done4, 1);
    lv_obj_set_y(ui_Done4, 82);
    lv_obj_set_align(ui_Done4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Done4, "SAVE");

    lv_obj_add_event_cb(ui_Done7, ui_event_Done7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Water_Purifier, ui_event_Water_Purifier, LV_EVENT_ALL, NULL);

}

void ui_Water_Purifier_screen_destroy(void)
{
    if(ui_Water_Purifier) lv_obj_del(ui_Water_Purifier);

    // NULL screen variables
    ui_Water_Purifier = NULL;
    ui_Dropdown4 = NULL;
    ui_Image12 = NULL;
    ui_Done7 = NULL;
    ui_Done4 = NULL;

}
